service: serverless-python
app: hands-on
org: krymtkts

provider:
  name: aws
  runtime: python3.8
  region: ap-northeast-1
  memorySize: 128
  timeout: 30
  iamManagedPolicies:
    - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
  logs:
    restApi: true

package:
  exclude:
    - ./**
  include:
    - handler.py

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: users/create
          method: get
